[package]
name = "rust_ui"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
fontdue = "0.7.2"
miniquad = { git = "https://github.com/not-fl3/miniquad", branch = "master" }
glam = "0.20.5"